# Generated by Django 4.2.20 on 2025-04-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glossary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="term",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="term_images/"),
        ),
    ]
