# Generated by Django 4.2.20 on 2025-04-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="question", name="text",),
        migrations.AddField(
            model_name="question",
            name="question_text",
            field=models.CharField(default="Пример вопроса", max_length=255),
        ),
        migrations.AlterField(
            model_name="question",
            name="correct_option",
            field=models.CharField(
                choices=[
                    ("A", "Option A"),
                    ("B", "Option B"),
                    ("C", "Option C"),
                    ("D", "Option D"),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="option_a",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="question",
            name="option_b",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="question",
            name="option_c",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="question",
            name="option_d",
            field=models.CharField(max_length=255),
        ),
    ]
