# Generated by Django 4.2.20 on 2025-04-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="correct_answer",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="card",
            name="quiz_question",
            field=models.CharField(
                blank=True, help_text="Вопрос для викторины", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="wrong_answer1",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="card",
            name="wrong_answer2",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
